export const jobData = {
  noOfJobs: 17983,
  clusters: {
    salaryRange: [
      {
        id: "6to10",
        count: 12009,
        label: "6-10 Lakhs",
      },
      {
        id: "10to15",
        count: 1914,
        label: "10-15 Lakhs",
      },
      {
        id: "15to25",
        count: 687,
        label: "15-25 Lakhs",
      },
      {
        id: "25to50",
        count: 378,
        label: "25-50 Lakhs",
      },
      {
        id: "50to75",
        count: 61,
        label: "50-75 Lakhs",
      },
      {
        id: "75to100",
        count: 2,
        label: "75-100 Lakhs",
      },
      {
        id: "100to500",
        count: 1,
        label: "1-5 Cr",
      },
      {
        id: "0to3",
        count: 4605,
        label: "0-3 Lakhs",
      },
      {
        id: "3to6",
        count: 15237,
        label: "3-6 Lakhs",
      },
    ],
    wfhType: [
      {
        id: "0",
        count: 17250,
        label: "Work from office",
      },
      {
        id: "2",
        count: 585,
        label: "Remote",
      },
      {
        id: "3",
        count: 148,
        label: "Hybrid",
      },
    ],
    topGroupId: [
      {
        id: "10476",
        count: 521,
        label: "Accenture",
      },
      {
        id: "13832",
        count: 146,
        label: "Infosys",
      },
      {
        id: "4619011",
        count: 35,
        label: "Photon",
      },
      {
        id: "1288",
        count: 32,
        label: "Capgemini",
      },
      {
        id: "216316",
        count: 17,
        label: "UST",
      },
      {
        id: "1402790",
        count: 16,
        label: "CGI",
      },
      {
        id: "530892",
        count: 16,
        label: "Goldman Sachs",
      },
      {
        id: "9558",
        count: 16,
        label: "Nagarro",
      },
      {
        id: "10472",
        count: 15,
        label: "eClerx",
      },
      {
        id: "2472988",
        count: 15,
        label: "Conduent",
      },
      {
        id: "255614",
        count: 15,
        label: "Google",
      },
      {
        id: "242",
        count: 14,
        label: "Bajaj Finance",
      },
      {
        id: "8483159",
        count: 13,
        label: "PwC Service Delivery Center",
      },
      {
        id: "243080",
        count: 12,
        label: "EY",
      },
      {
        id: "12466",
        count: 11,
        label: "Hexaware Technologies",
      },
    ],
    employement: [
      {
        id: "1",
        count: 17421,
        label: "Company Jobs",
      },
      {
        id: "2",
        count: 562,
        label: "Consultant Jobs",
      },
    ],
    featuredCompanies: [
      {
        id: "6762",
        count: 15,
        label: "Conduent",
        url: "/conduent-jobs-careers-6762?keyword=react.js%2C+react+developer%2C+mern&src=fcc&experience=2&companyId=6762",
      },
      {
        id: "479215",
        count: 1,
        label: "Opentext",
        url: "/job-listings-software-developer-opentext-technologies-india-pvt-ltd-bengaluru-1-to-6-years-140826914871",
      },
    ],
    business_size: [
      {
        id: "211",
        count: 3405,
        label: "Corporate",
      },
      {
        id: "213",
        count: 1472,
        label: "Foreign MNC",
      },
      {
        id: "62",
        count: 450,
        label: "Startup",
      },
      {
        id: "217",
        count: 445,
        label: "Indian MNC",
      },
      {
        id: "63",
        count: 29,
        label: "Others",
      },
      {
        id: "215",
        count: 2,
        label: "Govt/PSU",
      },
      {
        id: "60",
        count: 1,
        label: "MNC",
      },
    ],
    citiesGid: [
      {
        id: "139",
        count: 1467,
        label: "Pune",
      },
      {
        id: "97",
        count: 2604,
        label: "Bengaluru",
      },
      {
        id: "9508",
        count: 2545,
        label: "Delhi / NCR",
      },
      {
        id: "125",
        count: 1624,
        label: "Indore",
      },
      {
        id: "9509",
        count: 1483,
        label: "Mumbai (All Areas)",
      },
      {
        id: "134",
        count: 1349,
        label: "Mumbai",
      },
      {
        id: "17",
        count: 1292,
        label: "Hyderabad",
      },
      {
        id: "183",
        count: 1220,
        label: "Chennai",
      },
      {
        id: "6",
        count: 994,
        label: "New Delhi",
      },
      {
        id: "51",
        count: 919,
        label: "Ahmedabad",
      },
      {
        id: "220",
        count: 826,
        label: "Noida",
      },
      {
        id: "232",
        count: 676,
        label: "Kolkata",
      },
      {
        id: "73",
        count: 589,
        label: "Gurugram",
      },
      {
        id: "173",
        count: 449,
        label: "Jaipur",
      },
      {
        id: "64",
        count: 424,
        label: "Surat",
      },
      {
        id: "4",
        count: 336,
        label: "Chandigarh",
      },
      {
        id: "167",
        count: 286,
        label: "Mohali",
      },
      {
        id: "110",
        count: 275,
        label: "Kochi",
      },
      {
        id: "184",
        count: 271,
        label: "Coimbatore",
      },
      {
        id: "136",
        count: 213,
        label: "Nagpur",
      },
      {
        id: "65",
        count: 161,
        label: "Vadodara",
      },
      {
        id: "120",
        count: 157,
        label: "Thiruvananthapuram",
      },
      {
        id: "216",
        count: 136,
        label: "Lucknow",
      },
      {
        id: "323",
        count: 131,
        label: "Thane",
      },
      {
        id: "63",
        count: 130,
        label: "Rajkot",
      },
    ],
    functionalAreaGid: [
      {
        id: "5",
        count: 16623,
        label: "Engineering - Software & QA",
      },
      {
        id: "15",
        count: 564,
        label: "UX, Design & Architecture",
      },
      {
        id: "9",
        count: 119,
        label: "Marketing & Communication",
      },
      {
        id: "8",
        count: 116,
        label: "IT & Information Security",
      },
      {
        id: "20",
        count: 85,
        label: "Content, Editorial & Journalism",
      },
      {
        id: "3",
        count: 84,
        label: "Data Science & Analytics",
      },
      {
        id: "36",
        count: 58,
        label: "Teaching & Training",
      },
      {
        id: "4",
        count: 55,
        label: "Engineering - Hardware & Networks",
      },
      {
        id: "14",
        count: 41,
        label: "Sales & Business Development",
      },
      {
        id: "37",
        count: 37,
        label: "Other",
      },
      {
        id: "12",
        count: 33,
        label: "Project & Program Management",
      },
      {
        id: "19",
        count: 25,
        label: "Consulting",
      },
      {
        id: "2",
        count: 24,
        label: "Customer Success, Service & Operations",
      },
      {
        id: "6",
        count: 19,
        label: "Finance & Accounting",
      },
      {
        id: "7",
        count: 18,
        label: "Human Resources",
      },
    ],
    ugCourseGid: [
      {
        id: "11",
        count: 492,
        label: "B.Sc",
      },
      {
        id: "9502",
        count: 14937,
        label: "Any Graduate",
      },
      {
        id: "12",
        count: 3063,
        label: "B.Tech / B.E.",
      },
      {
        id: "4",
        count: 672,
        label: "B.C.A.",
      },
      {
        id: "15",
        count: 74,
        label: "Diploma",
      },
      {
        id: "9501",
        count: 50,
        label: "Graduation Not Required",
      },
      {
        id: "5",
        count: 26,
        label: "B.B.A. / B.M.S.",
      },
      {
        id: "2",
        count: 17,
        label: "B.A - Bachelor of Arts",
      },
      {
        id: "6",
        count: 16,
        label: "B.Com",
      },
      {
        id: "40",
        count: 5,
        label: "B.Des. - Bachelor of Design",
      },
      {
        id: "14",
        count: 2,
        label: "M.B.B.S.",
      },
      {
        id: "9999",
        count: 2,
        label: "Other Graduate",
      },
      {
        id: "7",
        count: 1,
        label: "B.Ed",
      },
    ],
    glbl_RoleCat: [
      {
        id: "1028",
        count: 15270,
        label: "Software Development",
      },
      {
        id: "1027",
        count: 841,
        label: "Quality Assurance and Testing",
      },
      {
        id: "1072",
        count: 359,
        label: "Other Design",
      },
      {
        id: "1025",
        count: 290,
        label: "DBA / Data warehousing",
      },
      {
        id: "1026",
        count: 222,
        label: "DevOps",
      },
      {
        id: "1071",
        count: 197,
        label: "UI / UX",
      },
      {
        id: "1048",
        count: 95,
        label: "Digital Marketing",
      },
      {
        id: "1085",
        count: 78,
        label: "Content Management (Print / Online / Electronic)",
      },
      {
        id: "1019",
        count: 49,
        label: "Data Science & Machine Learning",
      },
      {
        id: "1022",
        count: 46,
        label: "IT Network",
      },
    ],
    pgCourseGid: [
      {
        id: "11",
        count: 265,
        label: "MS/M.Sc(Science)",
      },
      {
        id: "9511",
        count: 14634,
        label: "Any Postgraduate",
      },
      {
        id: "14",
        count: 1080,
        label: "MCA",
      },
      {
        id: "9510",
        count: 1035,
        label: "Post Graduation Not Required",
      },
      {
        id: "12",
        count: 1011,
        label: "M.Tech",
      },
      {
        id: "5",
        count: 73,
        label: "LLM",
      },
      {
        id: "13",
        count: 67,
        label: "MBA/PGDM",
      },
      {
        id: "1",
        count: 21,
        label: "CA",
      },
      {
        id: "16",
        count: 20,
        label: "PG Diploma",
      },
      {
        id: "15",
        count: 14,
        label: "Medical-MS/MD",
      },
      {
        id: "6",
        count: 5,
        label: "M.A",
      },
      {
        id: "8",
        count: 5,
        label: "M.Com",
      },
    ],
    industryTypeGid: [
      {
        id: "109",
        count: 12602,
        label: "IT Services & Consulting",
      },
      {
        id: "102",
        count: 201,
        label: "BPM / BPO",
      },
      {
        id: "110",
        count: 671,
        label: "Software Product",
      },
      {
        id: "172",
        count: 656,
        label: "Advertising & Marketing",
      },
      {
        id: "127",
        count: 367,
        label: "Recruitment / Staffing",
      },
      {
        id: "126",
        count: 311,
        label: "Management Consulting",
      },
      {
        id: "133",
        count: 290,
        label: "Education / Training",
      },
      {
        id: "108",
        count: 247,
        label: "Internet",
      },
      {
        id: "113",
        count: 217,
        label: "Financial Services",
      },
      {
        id: "131",
        count: 189,
        label: "Medical Services / Hospital",
      },
      {
        id: "112",
        count: 159,
        label: "Banking",
      },
      {
        id: "128",
        count: 153,
        label: "Biotechnology",
      },
      {
        id: "134",
        count: 114,
        label: "E-Learning / EdTech",
      },
      {
        id: "175",
        count: 112,
        label: "Film / Music / Entertainment",
      },
      {
        id: "101",
        count: 102,
        label: "Analytics / KPO / Research",
      },
    ],
  },
  jobDetails: [
    {
      title: "Mean / Mern Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/11165482.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/11165482.gif",
      jobId: "140826504806",
      currency: "INR",
      footerPlaceholderLabel: "1 Day Ago",
      footerPlaceholderColor: "green",
      companyName: "Globally Web Solutions",
      isSaved: false,
      tagsAndSkills: "c#,css,python,c++,mern,bootstrap,scalability,javascript",
      placeholders: [
        {
          type: "experience",
          label: "1-4 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Jaipur",
        },
      ],
      companyId: 124400618,
      jdURL:
        "/job-listings-mean-mern-developer-globally-web-solutions-jaipur-1-to-4-years-140826504806",
      staticUrl: "globally-web-solutions-jobs-careers-124400618",
      jobDescription:
        "<ul> <li> Design, develop, and test software applications using Mean/Mern technologies. </li> <li> Collaborate with cross-functional teams to identify and prioritize project requirements. </li> <li> Develop high-quality, scalable, and efficient code. </li> <li> Troubleshoot and resolve technical issues efficiently. </li> <li> Participate in code reviews and contribute to improving overall code quality. </li> <li> Stay updated with the latest trends and technologies in Mean/Mern development. </li> </ul>\n\n Disclaimer: This job posting & Location has been aggregated from external source. Role details, content, and availability are subject to change. Applicants are advised to confirm the latest information directly on the company website before applying.",
      showMultipleApply: false,
      groupId: 11165482,
      isTopGroup: 0,
      createdDate: 1786713284000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-4 Yrs",
      minimumExperience: "1",
      maximumExperience: "4",
      applyByTime: "10:44 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=140826504806&logstr=srprestapi",
      applyRedirectUrl: "https://globallywebsolutions.com/careers",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/236112.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/236112.gif",
      jobId: "010626503442",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Prologic Technologies",
      isSaved: false,
      tagsAndSkills:
        "mern stack,css,software testing,software design,mern,problem solving,javascript,jquery",
      placeholders: [
        {
          type: "experience",
          label: "1-4 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Mohali",
        },
      ],
      companyId: 2788476,
      jdURL:
        "/job-listings-mern-developer-prologic-technologies-mohali-1-to-4-years-010626503442",
      staticUrl: "prologic-technologies-jobs-careers-915740",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/prologic-technologies-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 47,
        AggregateRating: "2.1",
        Title: "Prologic Technologies Reviews by Employees",
      },
      jobDescription:
        "<ul>\n<li>Design, develop, and maintain high-quality software applications using the MERN stack.</li>\n<li>Collaborate with cross-functional teams to identify and prioritize project requirements.</li>\n<li>Develop and implement robust data models and APIs to support application functionality.</li>\n<li>Ensure compliance with industry standards and best practices for coding, testing, and deployment.</li>\n<li>Participate in code reviews and contribute to improving overall code quality.</li>\n<li>Troubleshoot and resolve technical issues efficiently.</li>\n</ul>\n<h3>\n\nDisclaimer: This job posting has been aggregated from external source. Role details, content, and availability are subject to change. Applicants are advised to confirm the latest information directly on the company website before applying.</h3>",
      showMultipleApply: false,
      groupId: 236112,
      isTopGroup: 0,
      createdDate: 1780316209000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-4 Yrs",
      minimumExperience: "1",
      maximumExperience: "4",
      applyByTime: "9:46 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=010626503442&logstr=srprestapi",
      applyRedirectUrl: "https://www.prologic-technologies.com/career/",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN / MEAN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/4964456.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/4964456.gif",
      jobId: "200726501818",
      currency: "INR",
      footerPlaceholderLabel: "26 Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Jploft Solutions",
      isSaved: false,
      tagsAndSkills:
        "css,laravel,version control,mern,react,ajax,javascript,app development",
      placeholders: [
        {
          type: "experience",
          label: "1-4 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Jaipur",
        },
      ],
      companyId: 5515308,
      jdURL:
        "/job-listings-mern-mean-developer-jploft-solutions-pvt-ltd-jaipur-1-to-4-years-200726501818",
      staticUrl: "jploft-solutions-jobs-careers-4582344",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/jploft-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 86,
        AggregateRating: "4.0",
        Title: "JPLoft Solutions Reviews by Employees",
      },
      jobDescription:
        "Experience with version control systems (SVN,GIT) and build management tools<br><br>Experience in hybrid app development using Angular,Ionic,and Django is a plus. Disclaimer: This job posting has been aggregated from external source",
      showMultipleApply: false,
      groupId: 4964456,
      isTopGroup: 0,
      createdDate: 1784544820000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-4 Yrs",
      minimumExperience: "1",
      maximumExperience: "4",
      applyByTime: "8:23 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=200726501818&logstr=srprestapi",
      applyRedirectUrl: "https://www.jploft.com/career-at-jploft#find_job_sec",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/7600779.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/7600779.gif",
      jobId: "280525504535",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Neuro Spark Works",
      isSaved: false,
      tagsAndSkills:
        "schema,css,c++,web application,bootstrap,jquery,sql,react.js",
      placeholders: [
        {
          type: "experience",
          label: "1-4 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Pune",
        },
      ],
      companyId: 124593596,
      jdURL:
        "/job-listings-mern-developer-neuro-spark-works-solutions-pune-1-to-4-years-280525504535",
      staticUrl: "neuro-spark-works-jobs-careers-124593596",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/neuro-spark-works-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 3,
        AggregateRating: "4.8",
        Title: "Neuro Spark Works Reviews by Employees",
      },
      jobDescription:
        "Neuro Spark Works Solutions is looking for MERN developer to join our dynamic team and embark on a rewarding career journey Developing and implementing web applications using the MERN stack, adhering to best practices and coding standards <br /> <br /> Designing and implementing database schemas and ensuring efficient data retrieval and storage <br /> <br /> Building server-side APIs and implementing RESTful services to handle data requests and responses <br /> <br /> Creating interactive and user-friendly front-end interfaces using React <br /> <br /> js, incorporating state management and UI libraries as needed <br /> <br /> Integrating the front-end and back-end components of the application to ensure seamless data flow and functionality <br /> <br /> Collaborating with designers, product managers, and other team members to gather requirements, provide input on system design, and deliver high-quality software <br /> <br /> Conducting testing and debugging to ensure application functionality, performance, and security <br /> <br /> Keeping up to date with emerging technologies and trends in the MERN stack and web development field",
      showMultipleApply: false,
      groupId: 7600779,
      isTopGroup: 0,
      createdDate: 1748433124000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-4 Yrs",
      minimumExperience: "1",
      maximumExperience: "4",
      applyByTime: "9:22 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=280525504535&logstr=srprestapi",
      applyRedirectUrl: "https://neurosparkworks.com/careers/",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/2507918.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/2507918.gif",
      jobId: "301025504886",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Purgesoft",
      isSaved: false,
      tagsAndSkills:
        "server,redux,css,dom,server side,sharepoint,bootstrap,ajax",
      placeholders: [
        {
          type: "experience",
          label: "1-4 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Jaipur",
        },
      ],
      companyId: 125182623,
      jdURL:
        "/job-listings-mern-developer-purgesoft-jaipur-1-to-4-years-301025504886",
      staticUrl: "purgesoft-jobs-careers-4654370",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/purgesoft-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 18,
        AggregateRating: "3.7",
        Title: "Purgesoft Reviews by Employees",
      },
      jobDescription:
        "Thorough understanding of React.js and its core principles . Hands-on experience with JavaScript Development on both client and server-side",
      showMultipleApply: false,
      groupId: 2507918,
      isTopGroup: 0,
      createdDate: 1761828280000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-4 Yrs",
      minimumExperience: "1",
      maximumExperience: "4",
      applyByTime: "10:14 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=301025504886&logstr=srprestapi",
      applyRedirectUrl: "https://purgesoft.com/career",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/6296667.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/6296667.gif",
      jobId: "190925502952",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Porak Technologies",
      isSaved: false,
      tagsAndSkills:
        "schema,css,c++,web application,bootstrap,jquery,sql,react.js",
      placeholders: [
        {
          type: "experience",
          label: "1-4 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Kochi",
        },
      ],
      companyId: 125097421,
      jdURL:
        "/job-listings-mern-developer-pokak-technologies-pvt-ltd-kochi-1-to-4-years-190925502952",
      staticUrl: "porak-technologies-jobs-careers-125097421",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/porak-technologies-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 7,
        AggregateRating: "2.8",
        Title: "Porak Technologies Reviews by Employees",
      },
      jobDescription:
        "POKAK Technologies pvt LTD is looking for MERN Developer to join our dynamic team and embark on a rewarding career journey Developing and implementing web applications using the MERN stack, adhering to best practices and coding standards  <br /> <br /> Designing and implementing database schemas and ensuring efficient data retrieval and storage  <br /> <br /> Building server-side APIs and implementing RESTful services to handle data requests and responses  <br /> <br /> Creating interactive and user-friendly front-end interfaces using React  <br /> <br /> js, incorporating state management and UI libraries as needed  <br /> <br /> Integrating the front-end and back-end components of the application to ensure seamless data flow and functionality  <br /> <br /> Collaborating with designers, product managers, and other team members to gather requirements, provide input on system design, and deliver high-quality software  <br /> <br /> Conducting testing and debugging to ensure application functionality, performance, and security  <br /> <br /> Keeping up to date with emerging technologies and trends in the MERN stack and web development field",
      showMultipleApply: false,
      groupId: 6296667,
      isTopGroup: 0,
      createdDate: 1758281933000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-4 Yrs",
      minimumExperience: "1",
      maximumExperience: "4",
      applyByTime: "9:08 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=190925502952&logstr=srprestapi",
      applyRedirectUrl: "https://pokaktech.com/careers",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/7510367.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/7510367.gif",
      jobId: "150526502869",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Bootcoding",
      isSaved: false,
      tagsAndSkills:
        "c#,css,python,c,mern,ms dynamics crm,bootstrap,javascript",
      placeholders: [
        {
          type: "experience",
          label: "1-3 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Nagpur",
        },
      ],
      companyId: 125602126,
      jdURL:
        "/job-listings-mern-developer-bootcoding-nagpur-1-to-3-years-150526502869",
      staticUrl: "bootcoding-jobs-careers-125602126",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/bootcoding-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 3,
        AggregateRating: "4.0",
        Title: "Bootcoding Reviews by Employees",
      },
      jobDescription:
        "<ul>\n<li>Design, develop, and maintain scalable and efficient software applications using the MERN stack.</li>\n<li>Collaborate with front-end developers to integrate user interfaces with back-end services.</li>\n<li>Develop high-quality code that meets industry standards and best practices.</li>\n<li>Participate in code reviews and contribute to improving overall code quality.</li>\n<li>Troubleshoot and resolve technical issues efficiently.</li>\n<li>Stay updated with the latest trends and technologies in the MERN stack.</li>\n</ul>\n<h3>\n\nDisclaimer: This job posting has been aggregated from external source. Role details, content, and availability are subject to change. Applicants are advised to confirm the latest information directly on the company website before applying.</h3>",
      showMultipleApply: false,
      groupId: 7510367,
      isTopGroup: 0,
      createdDate: 1778831187000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-3 Yrs",
      minimumExperience: "1",
      maximumExperience: "3",
      applyByTime: "5:16 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=150526502869&logstr=srprestapi",
      applyRedirectUrl:
        "https://interview.aceint.ai/backend/api/v1/jobs/jobs/MD-5584",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title:
        "Junior MERN Stack Developer (React-Focused | AI-First Environment)",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/3486020.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/3486020.gif",
      jobId: "070426502588",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Sigosoft",
      isSaved: false,
      tagsAndSkills:
        "Backend,Version control,GIT,Coding,Debugging,System integration,Javascript,Data structures",
      placeholders: [
        {
          type: "experience",
          label: "2-6 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Kochi, Thrissur, Kozhikode, Thiruvananthapuram",
        },
      ],
      companyId: 4874390,
      jdURL:
        "/job-listings-junior-mern-stack-developer-react-focused-ai-first-environment-sigosoft-private-limited-kochi-thrissur-kozhikode-thiruvananthapuram-2-to-6-years-070426502588",
      staticUrl: "sigosoft-jobs-careers-4874390",
      jobDescription:
        "<div> This is not a basic MERN stack role. </div> <div> We are looking for a  <strong> highly accountable MERN Stack developer with strong React expertise </strong>  who will take ownership of frontend architecture, system integration, and delivery quality across web applications. </div> <div> You will work in an  <strong> AI-first development environment </strong> , where tools like Cursor, ChatGPT, and AI-assisted debugging are mandatory in daily workflow. </div> <div> Your primary focus is  <strong> React development </strong> , but you are also expected to understand backend flow, API contracts, and system behaviour end-to-end. </div> Core Ownership  <div> You are responsible for: </div> <ul> <li> Frontend architecture and code quality </li> <li> UI performance and responsiveness </li> <li> API integration stability </li> <li> Consistency across screens and modules </li> <li> Preventing UI/logic-related production issues </li> <li> Ensuring what is built matches design and scope </li> </ul> <div> If frontend issues affect user experience or delivery, it falls under your accountability. </div> React-Focused Responsibilities  <ul> <li> Build scalable and maintainable applications using React </li> <li> Implement structured component architecture </li> <li> Manage state using modern approaches (Context / Redux / Zustand or similar) </li> <li> Ensure reusable and clean component design </li> <li> Handle API integration and data flow </li> <li> Optimize rendering and performance </li> <li> Implement responsive UI across devices </li> <li> Ensure consistency with UI/UX designs </li> </ul> MERN & System Responsibilities  <ul> <li> Understand backend flow (Node.js / Express) </li> <li> Work with MongoDB data structures (basic level) </li> <li> Validate API responses and error handling </li> <li> Ensure frontend-backend integration stability </li> <li> Support debugging across layers when required </li> </ul> Operational & Delivery Responsibility  <ul> <li> Break down features into structured frontend tasks </li> <li> Estimate timelines realistically </li> <li> Maintain clean code and folder structure </li> <li> Follow strict Git workflow and version control </li> <li> Validate builds before QA handover </li> <li> Maintain proper documentation where required </li> <li> Communicate blockers early </li> </ul> AI-Integrated Responsibilities  <ul> <li> Use AI tools (Cursor, ChatGPT, AI coding assistants) daily </li> <li> Use AI for:  <ul> <li> Component structuring </li> <li> Code optimization </li> <li> Debugging assistance </li> <li> Performance improvement suggestions </li> <li> API integration validation </li> </ul> </li> <li> Increase development speed using AI without reducing quality </li> </ul> <div> AI usage is mandatory. Manual-only development is not acceptable. </div> Required Skills  <ul> <li> Strong expertise in React (Mandatory) </li> <li> Good knowledge of JavaScript (ES6+) </li> <li> Strong understanding of component-based architecture </li> <li> Experience with state management </li> <li> Experience integrating REST APIs </li> <li> Understanding of responsive design </li> <li> Basic knowledge of Node.js and Express </li> <li> Basic understanding of MongoDB </li> <li> Experience with Git </li> <li> Experience using AI coding tools like Cursor (Mandatory) </li> <li> Strong problem-solving skills </li> <li> Candidate must be from Kerala </li> </ul> Good to Have  <ul> <li> Experience with Next.js </li> <li> Knowledge of performance optimization techniques </li> <li> Basic understanding of UI/UX principles </li> <li> Experience with TypeScript </li> </ul> What This Role Is Not  <ul> <li> Not just converting designs to UI </li> <li> Not limited to writing components </li> <li> Not a task-based execution role </li> </ul> <div> This is a  <strong> frontend ownership and system responsibility role </strong> . </div> Ideal Candidate  <ul> <li> Strong focus on quality and structure </li> <li> Can think beyond UI into system behaviour </li> <li> Comfortable handling responsibility </li> <li> Able to manage multiple modules simultaneously </li> <li> Ready to work in a high-performance environment </li> </ul> <div> </div> <div> </div> <div> <div> <div> <div> </div> </div> </div> </div>",
      showMultipleApply: false,
      groupId: 3486020,
      isTopGroup: 0,
      createdDate: 1775566274000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "Associate level",
      minimumExperience: "2",
      maximumExperience: "6",
      applyByTime: "10:21 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=070426502588&logstr=srprestapi",
      applyRedirectUrl: "https://sigosoft.com/blog/jobs/mern-stack-developer/",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "Software Engineer (MERN)",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/8425909.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/8425909.gif",
      jobId: "100325502452",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Velsera",
      isSaved: false,
      tagsAndSkills:
        "Front end,Database design,Healthcare,HTML,Application development,Scrum,biomedical,Analytics",
      placeholders: [
        {
          type: "experience",
          label: "0-4 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Pune",
        },
      ],
      companyId: 123919245,
      jdURL:
        "/job-listings-software-engineer-mern-velsera-pune-0-to-4-years-100325502452",
      staticUrl: "velsera-jobs-careers-123919245",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/velsera-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 51,
        AggregateRating: "2.6",
        Title: "Velsera Reviews by Employees",
      },
      jobDescription:
        "Competencies:  . At least 3 years of Software Development professional experience on MERN or MEAN stack . Hands-on development and Proficient excellence in Node.js building REST based micro services . In-depth knowledge of Node.js frameworks such as Express.js and NEST . <br><br>Experience in communicating and coordinating with distributed team across the world",
      showMultipleApply: false,
      groupId: 8425909,
      isTopGroup: 0,
      createdDate: 1741611328000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "0-4 Yrs",
      minimumExperience: "0",
      maximumExperience: "4",
      applyByTime: "10:25 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=100325502452&logstr=srprestapi",
      applyRedirectUrl:
        "https://velsera.wd103.myworkdayjobs.com/en-US/Velsera/job/Pune-India/Software-Engineer--MERN-_JR100355",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN / MEAN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/5943870.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/5943870.gif",
      jobId: "240523500356",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Adiyogi Technosoft",
      isSaved: false,
      tagsAndSkills:
        "Ubuntu,System architecture,NoSQL,Web technologies,Linux,MySQL,Javascript,MongoDB",
      placeholders: [
        {
          type: "experience",
          label: "2-6 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Jodhpur",
        },
      ],
      companyId: 123805743,
      jdURL:
        "/job-listings-mern-mean-developer-adiyogi-technosoft-pvt-ltd-jodhpur-2-to-6-years-240523500356",
      staticUrl: "adiyogi-technosoft-jobs-careers-6577436",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/adiyogi-technosoft-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 8,
        AggregateRating: "4.6",
        Title: "Adiyogi Technosoft Reviews by Employees",
      },
      jobDescription:
        "Hands-on experience in writing applications using Node Js (Express). 1- Must be good in MySQL or one of the databases such as Mongo. 2- Should be proficient in Linux or Ubuntu Environment with complete knowledge of Application deployment",
      showMultipleApply: false,
      groupId: 5943870,
      isTopGroup: 0,
      createdDate: 1684940090000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "Associate level",
      minimumExperience: "2",
      maximumExperience: "6",
      applyByTime: "12:24 AM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=240523500356&logstr=srprestapi",
      applyRedirectUrl: "https://adiyogitechnosoft.com/career-detail/MEAN/MERN",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/4149294.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/4149294.gif",
      jobId: "050424500635",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "AMS Digital",
      isSaved: false,
      tagsAndSkills:
        "PSD,GIT,NoSQL,RDBMS,Debugging,Javascript,Performance testing,HTML",
      placeholders: [
        {
          type: "experience",
          label: "2-3 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "New Delhi",
        },
      ],
      companyId: 4988234,
      jdURL:
        "/job-listings-mern-developer-ams-digital-new-delhi-2-to-3-years-050424500635",
      staticUrl: "ams-digital-jobs-careers-4988234",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/ams-digital-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 5,
        AggregateRating: "5.0",
        Title: "AMS Digital Reviews by Employees",
      },
      jobDescription:
        "Implementation of security and data protection . Understanding of performance testing and optimization techniques . MERN software developer must have good communication interpersonal skills . Ability to work independently with minimum supervision<br><br> MERN stack developers should have the ability to translate Wireframes and PSD Designs into functional",
      showMultipleApply: false,
      groupId: 4149294,
      isTopGroup: 0,
      createdDate: 1712315602000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "Associate level",
      minimumExperience: "2",
      maximumExperience: "3",
      applyByTime: "8:43 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=050424500635&logstr=srprestapi",
      applyRedirectUrl:
        "https://www.amsdigital.in/career/mern-developers-jobs-delhi-ncr.php",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/4149294.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/4149294.gif",
      jobId: "020126500280",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "AMS Digital",
      isSaved: false,
      tagsAndSkills:
        "PSD,GIT,NoSQL,HP data protector,RDBMS,Debugging,Javascript,Performance testing",
      placeholders: [
        {
          type: "experience",
          label: "2-3 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "New Delhi",
        },
      ],
      companyId: 4988234,
      jdURL:
        "/job-listings-mern-developer-ams-digital-new-delhi-2-to-3-years-020126500280",
      staticUrl: "ams-digital-jobs-careers-4988234",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/ams-digital-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 5,
        AggregateRating: "5.0",
        Title: "AMS Digital Reviews by Employees",
      },
      jobDescription:
        "<li> Binding of UI elements to JavaScript object models  </li><li> </li><li> Creating RESTful services with Node.js  </li><li> </li><li> MERN stack developer must have proven experience in front & back-end development  </li><li> </li><li> Work in a cross-functional team to deliver a complete user experience  </li><li> </li><li> Reactjs Nodejs developers must know MongoDB, Express, Node.js, & React.  </li><li> </li><li> Create Unit and Integration tests to ensure the quality of code  </li><li> </li><li> Be responsive to change requests and feature requests  </li><li> </li><li> Write code that is cross-platform and cross-device compatible  </li><li> </li><li> For MERN stack developer job, candidate must have good Knowledge of Node Debugging  </li><li> </li><li> Understanding & proficiency in REST APIs.  </li><li> </li><li> MERN stack developer should know Git Repository and Jira  </li><li> </li><li> Integration of data storage solutions [RDBMS, NoSQL DB]  </li><li> <div> Responsibilities & Skills  <ul> <li> MERN Fullstack eCommerce developer is responsible for writing reusable, testable, and efficient code  </li><li> </li><li> Design and implementation of low-latency, high-availability, and performant applications  </li><li> </li><li> Implementation of security and data protection  </li><li> </li><li> Understanding of performance testing and optimization techniques  </li><li> </li><li> MERN software developer must have good communication & interpersonal skills  </li><li> </li><li> Ability to work independently with minimum supervision.  </li><li> <ul> <div> <p> 2-3 Years  </p><p> Please Share Your Info to  <br /> <strong> Get a Call from Us <strong> </strong> </strong> </p> </div> </ul> </li> </ul> </div> </li>",
      showMultipleApply: false,
      groupId: 4149294,
      isTopGroup: 0,
      createdDate: 1767337136000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "Associate level",
      minimumExperience: "2",
      maximumExperience: "3",
      applyByTime: "4:28 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=020126500280&logstr=srprestapi",
      applyRedirectUrl:
        "https://www.amsdigital.in/career/mern-developers-jobs-delhi-ncr.php",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "Mid MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/3083850.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/3083850.gif",
      jobId: "240425501354",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Solutionchamps Technologies",
      isSaved: false,
      tagsAndSkills:
        "Backend,Front end,Version control,GIT,Web technologies,Analytical,Javascript,MongoDB",
      placeholders: [
        {
          type: "experience",
          label: "2-4 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Coimbatore",
        },
      ],
      companyId: 3834022,
      jdURL:
        "/job-listings-mid-mern-developer-solutionchamps-technologies-pvt-ltd-coimbatore-2-to-4-years-240425501354",
      staticUrl: "solutionchamps-technologies-jobs-careers-2779646",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/solutionchamps-technologies-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 8,
        AggregateRating: "3.7",
        Title: "SolutionChamps Technologies Reviews by Employees",
      },
      jobDescription:
        "Good communication and teamwork skills <br><br>Experience : 2-4 years",
      showMultipleApply: false,
      groupId: 3083850,
      isTopGroup: 0,
      createdDate: 1745498377000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "Associate level",
      minimumExperience: "2",
      maximumExperience: "4",
      applyByTime: "10:09 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=240425501354&logstr=srprestapi",
      applyRedirectUrl: "https://solutionchamps.com/mid-mern-developer",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/6092327.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/6092327.gif",
      jobId: "230626505084",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "21twelve Interactive",
      isSaved: false,
      tagsAndSkills:
        "Computer vision,Web application development,Automation,Focus,Automation tools,Javascript,MongoDB,Natural language processing",
      placeholders: [
        {
          type: "experience",
          label: "1-6 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Ahmedabad",
        },
      ],
      companyId: 123888015,
      jdURL:
        "/job-listings-mern-developer-21twelve-interactive-ahmedabad-1-to-6-years-230626505084",
      staticUrl: "21twelve-interactive-jobs-careers-123888015",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/21twelve-interactive-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 3,
        AggregateRating: "3.4",
        Title: "21Twelve Interactive Reviews by Employees",
      },
      jobDescription:
        "Proven experience or projects integrating AI into web applications<br><br> Job Types: Full-time,Permanent,Fresher . Pay: 5,000 - 20,000 per month . Disclaimer : This job posting has been aggregated from external source<br><br>Requirements:  . 6 months to 1 year of experience as a MERN Developer<br><br>Experience with automation tools (n8n,Zapier,Make) is a plus",
      showMultipleApply: false,
      groupId: 6092327,
      isTopGroup: 0,
      createdDate: 1782216746000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-6 Yrs",
      minimumExperience: "1",
      maximumExperience: "6",
      applyByTime: "9:42 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=230626505084&logstr=srprestapi",
      applyRedirectUrl: "https://www.21twelveinteractive.com/career/",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/7510367.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/7510367.gif",
      jobId: "150526505480",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Bootcoding",
      isSaved: false,
      tagsAndSkills:
        "Health insurance,Backend,Front end,Version control,GIT,Database design,Agile,MongoDB",
      placeholders: [
        {
          type: "experience",
          label: "1-3 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Nagpur",
        },
      ],
      companyId: 125602126,
      jdURL:
        "/job-listings-mern-developer-bootcoding-nagpur-1-to-3-years-150526505480",
      staticUrl: "bootcoding-jobs-careers-125602126",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/bootcoding-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 3,
        AggregateRating: "4.0",
        Title: "Bootcoding Reviews by Employees",
      },
      jobDescription:
        "<div> We are seeking a motivated MERN Developer with 1 to 3 years of experience to join our dynamic team. The candidate will be responsible for developing and maintaining web applications using MongoDB, Express.js, React.js, and Node.js. This role requires a strong understanding of both front-end and back-end technologies to deliver seamless user experiences and robust server-side solutions. </div> Responsibilities  <ul> <li> Develop and maintain web applications using the MERN stack. </li> <li> Collaborate with cross-functional teams to define, design, and ship new features. </li> <li> Write clean, scalable, and efficient code following industry best practices. </li> <li> Troubleshoot, debug, and optimize application performance. </li> <li> Participate in code reviews and contribute to team knowledge sharing. </li> </ul> Qualifications  <ul> <li> 1 to 3 years of experience working with the MERN stack. </li> <li> Strong proficiency in JavaScript, including ES6+ syntax. </li> <li> Experience with RESTful API development and integration. </li> <li> Good understanding of database design and management using MongoDB. </li> <li> Familiarity with version control systems such as Git. </li> </ul> Preferred skills  <ul> <li> Experience with CI/CD pipelines and DevOps practices. </li> <li> Knowledge of TypeScript is a plus. </li> <li> Familiarity with containerization tools like Docker. </li> <li> Understanding of Agile methodologies. </li> </ul> Education  <ul> <li> Bachelors degree in Computer Science or a related field </li> <li> Diploma in Software Development or equivalent </li> </ul>\n\nDisclaimer : This job posting has been aggregated from external source. Role details, content, and availability are subject to change. Applicants are advised to confirm the latest information directly on the company website before applying.",
      showMultipleApply: false,
      groupId: 7510367,
      isTopGroup: 0,
      createdDate: 1778849675000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "1-3 Yrs",
      minimumExperience: "1",
      maximumExperience: "3",
      applyByTime: "10:24 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=150526505480&logstr=srprestapi",
      applyRedirectUrl:
        "https://interview.aceint.ai/backend/api/v1/jobs/jobs/MD-4825",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: true,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/8552685.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/8552685.gif",
      jobId: "020725504042",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Nural Tech",
      isSaved: false,
      tagsAndSkills:
        "ERP,Automation,Backend,Debugging,Javascript,Agile,Data structures,Scrum",
      placeholders: [
        {
          type: "experience",
          label: "2-3 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Gurugram",
        },
      ],
      companyId: 123734761,
      jdURL:
        "/job-listings-mern-developer-nural-tech-gurugram-2-to-3-years-020725504042",
      staticUrl: "nural-tech-jobs-careers-123734761",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/nuraltech-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 21,
        AggregateRating: "4.2",
        Title: "Nuraltech Private Limited Reviews by Employees",
      },
      jobDescription:
        "A MERN developer should be proficient in using Git to manage code changes,collaborate with other developers,and maintain code quality<br><br> . Key Skills Required:  . <br><br>The candidate must have strong knowledge in the following areas:  . JavaScript . MongoDB . Express.js . React.js . Node.js . Git . Agile Development",
      showMultipleApply: false,
      groupId: 8552685,
      isTopGroup: 0,
      createdDate: 1751454783000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "Associate level",
      minimumExperience: "2",
      maximumExperience: "3",
      applyByTime: "8:43 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=020725504042&logstr=srprestapi",
      applyRedirectUrl: "https://nuraltech.com/career/mern-developer/",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/11719767.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/11719767.gif",
      jobId: "170626500568",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Tvm Infotech",
      isSaved: false,
      tagsAndSkills:
        "Version control,Front end,Web technologies,Javascript,MongoDB,Control,Front,Mern",
      placeholders: [
        {
          type: "experience",
          label: "0-2 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Chennai",
        },
      ],
      companyId: 125672846,
      jdURL:
        "/job-listings-mern-developer-tvminfotech-private-limited-chennai-0-to-2-years-170626500568",
      staticUrl: "tvm-infotech-jobs-careers-124548532",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/tvm-infotech-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 12,
        AggregateRating: "3.8",
        Title: "TVM Infotech Reviews by Employees",
      },
      jobDescription:
        "<div> We are looking for a skilled MERN Developer with 2 to 7 years of experience to develop web applications using MongoDB, Express, React, and Node.js. The ideal candidate will have experience in writing RESTful APIs and integrating with the frontend. This position is located in Trivandrum/Thiruvananthapuram. </div> Roles and Responsibility  <ul> <li> Develop high-quality web applications using MongoDB, Express, React, and Node.js. </li> <li> Write efficient and well-documented RESTful APIs to integrate with the frontend. </li> <li> Maintain code quality and manage version control systems. </li> <li> Collaborate with cross-functional teams to identify and prioritize project requirements. </li> <li> Design and implement scalable and reliable architectures for web applications. </li> <li> Troubleshoot and resolve technical issues efficiently. </li> </ul> Job Requirements  <ul> <li> Proficiency in MongoDB, Express, React, and Node.js. </li> <li> Experience in writing RESTful APIs and integrating with the frontend. </li> <li> Strong understanding of software development principles and patterns. </li> <li> Excellent problem-solving skills and attention to detail. </li> <li> Ability to work collaboratively in a team environment. </li> <li> Strong communication and interpersonal skills. </li> </ul> About Company  <div> TVMINFOTECH PRIVATE LIMITED is a leading company in the industry, committed to delivering high-quality solutions and services to its clients. </div>\n\nDisclaimer : This job posting has been aggregated from external source. Role details, content, and availability are subject to change. Applicants are advised to confirm the latest information directly on the company website before applying.",
      showMultipleApply: false,
      groupId: 11719767,
      isTopGroup: 0,
      createdDate: 1781679940000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "0-2 Yrs",
      minimumExperience: "0",
      maximumExperience: "2",
      applyByTime: "4:35 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=170626500568&logstr=srprestapi",
      applyRedirectUrl: "https://www.tvminfotech.com/carrer.html",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/3840814.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/3840814.gif",
      jobId: "261224503390",
      currency: "INR",
      footerPlaceholderLabel: "30+ Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Zed Axis",
      isSaved: false,
      tagsAndSkills: "MERN Developer,Development,Mern",
      placeholders: [
        {
          type: "experience",
          label: "2-3 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Gurugram",
        },
      ],
      companyId: 4702478,
      jdURL:
        "/job-listings-mern-developer-zed-axis-technologies-gurugram-2-to-3-years-261224503390",
      staticUrl: "zed-axis-jobs-careers-2770",
      ambitionBoxData: {
        Url: "https://www.ambitionbox.com/reviews/zed-axis-technologies-reviews?utm_campaign=srp_ratings&utm_medium=desktop&utm_source=naukri&cvid=1ebaf3fb1dbc458fb2e29f54c0d91e4f",
        ReviewsCount: 7,
        AggregateRating: "4.1",
        Title: "Zed-Axis Technologies Reviews by Employees",
      },
      jobDescription:
        "Developing and implementing web applications using the MERN stack, adhering to best practices and coding standards. Designing and implementing database schemas and ensuring efficient data retrieval and storage. Building server-side APIs and implementing RESTful services to handle data requests and responses. Creating interactive and user-friendly front-end interfaces using React. js, incorporating state management and UI libraries as needed. Integrating the front-end and back-end components of the application to ensure seamless data flow and functionality. Collaborating with designers, product managers, and other team members to gather requirements, provide input on system design, and deliver high-quality software. Conducting testing and debugging to ensure application functionality, performance, and security. Keeping up to date with emerging technologies and trends in the MERN stack and web development field.",
      showMultipleApply: false,
      groupId: 3840814,
      isTopGroup: 0,
      createdDate: 1735222474000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "Associate level",
      minimumExperience: "2",
      maximumExperience: "3",
      applyByTime: "11:44 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=261224503390&logstr=srprestapi",
      applyRedirectUrl: "https://nuraltech.com/careers/",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
    {
      title: "MERN Stack Developer",
      logoPath: "https://img.naukimg.com/logo_images/groups/v1/12030015.gif",
      logoPathV3: "https://img.naukimg.com/logo_images/groups/v1/12030015.gif",
      jobId: "130826500071",
      currency: "INR",
      footerPlaceholderLabel: "2 Days Ago",
      footerPlaceholderColor: "grey",
      companyName: "Tatpata",
      isSaved: false,
      tagsAndSkills: "redux,css,restful,mean stack,js,express,react,cloud",
      placeholders: [
        {
          type: "experience",
          label: "2-5 Yrs",
        },
        {
          type: "salary",
          label: "Not disclosed",
        },
        {
          type: "location",
          label: "Bengaluru",
        },
      ],
      companyId: 125119159,
      jdURL:
        "/job-listings-mern-stack-developer-tatpara-bengaluru-2-to-5-years-130826500071",
      staticUrl: "tatpata-jobs-careers-125119159",
      jobDescription:
        "We are looking for a highly motivated and enthusiastic IoT Intern to join our team in Indore,specializing in Drone Technology<br><br>The ideal candidate should have 3+ years of experience or be a fresher with a strong foundation in computer science and engineering principles.  <br><br>Experience with programming languages such as Python,C++,Java,or similar.",
      showMultipleApply: false,
      groupId: 12030015,
      isTopGroup: 0,
      createdDate: 1786611031000,
      mode: "crawled",
      board: "1",
      salaryDetail: {
        minimumSalary: 0,
        maximumSalary: 0,
        currency: "INR",
        hideSalary: true,
        variablePercentage: 0,
        minSalaryPerMonth: 0,
        maxSalaryPerMonth: 0,
        ctcBreakup: {},
      },
      experienceText: "Associate level",
      minimumExperience: "2",
      maximumExperience: "5",
      applyByTime: "6:20 PM",
      companyApplyJob: true,
      walkinJob: false,
      companyApplyUrl:
        "https://www.naukri.com/cloudgateway-apply/apply-services/v0/apply/saveCompanyApply?id=&file=130826500071&logstr=srprestapi",
      applyRedirectUrl: "https://tatpara.com/mern-stack-developer/",
      segmentedTemplateId: "Template1",
      questionnaireIdPresent: false,
      roleCategoryGid: "1028",
      todaysJob: false,
      jobAgentEligle: false,
      saved: false,
    },
  ],
  fatFooter: [
    {
      tab: "Bangalore",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Bangalore",
          url: "https://www.naukri.com/software-engineer-jobs-in-bangalore",
        },
        {
          text: "Front End Developer Jobs In Bangalore",
          url: "https://www.naukri.com/front-end-developer-jobs-in-bangalore",
        },
        {
          text: "Fullstack Developer Jobs In Bangalore",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-bangalore",
        },
        {
          text: "Technical Lead Jobs In Bangalore",
          url: "https://www.naukri.com/technical-lead-jobs-in-bangalore",
        },
        {
          text: "Ui Developer Jobs In Bangalore",
          url: "https://www.naukri.com/ui-developer-jobs-in-bangalore",
        },
        {
          text: "Web Developer Jobs In Bangalore",
          url: "https://www.naukri.com/web-developer-jobs-in-bangalore",
        },
        {
          text: "System Engineer Jobs In Bangalore",
          url: "https://www.naukri.com/system-engineer-jobs-in-bangalore",
        },
        {
          text: "Associate Jobs In Bangalore",
          url: "https://www.naukri.com/associate-jobs-in-bangalore",
        },
        {
          text: "Consultant Jobs In Bangalore",
          url: "https://www.naukri.com/consultant-jobs-in-bangalore",
        },
        {
          text: "Technology Analyst Jobs In Bangalore",
          url: "https://www.naukri.com/technology-analyst-jobs-in-bangalore",
        },
      ],
    },
    {
      tab: "Delhi NCR",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Delhi NCR",
          url: "https://www.naukri.com/software-engineer-jobs-in-delhi-ncr",
        },
        {
          text: "Front End Developer Jobs In Delhi NCR",
          url: "https://www.naukri.com/front-end-developer-jobs-in-delhi-ncr",
        },
        {
          text: "Fullstack Developer Jobs In Delhi NCR",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-delhi-ncr",
        },
        {
          text: "Technical Lead Jobs In Delhi NCR",
          url: "https://www.naukri.com/technical-lead-jobs-in-delhi-ncr",
        },
        {
          text: "Ui Developer Jobs In Delhi NCR",
          url: "https://www.naukri.com/ui-developer-jobs-in-delhi-ncr",
        },
        {
          text: "Web Developer Jobs In Delhi NCR",
          url: "https://www.naukri.com/web-developer-jobs-in-delhi-ncr",
        },
        {
          text: "System Engineer Jobs In Delhi NCR",
          url: "https://www.naukri.com/system-engineer-jobs-in-delhi-ncr",
        },
        {
          text: "Associate Jobs In Delhi NCR",
          url: "https://www.naukri.com/associate-jobs-in-delhi-ncr",
        },
        {
          text: "Consultant Jobs In Delhi NCR",
          url: "https://www.naukri.com/consultant-jobs-in-delhi-ncr",
        },
        {
          text: "Technology Analyst Jobs In Delhi NCR",
          url: "https://www.naukri.com/technology-analyst-jobs-in-delhi-ncr",
        },
      ],
    },
    {
      tab: "Hyderabad Secunderabad",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/software-engineer-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "Front End Developer Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/front-end-developer-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "Fullstack Developer Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "Technical Lead Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/technical-lead-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "Ui Developer Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/ui-developer-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "Web Developer Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/web-developer-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "System Engineer Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/system-engineer-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "Associate Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/associate-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "Consultant Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/consultant-jobs-in-hyderabad-secunderabad",
        },
        {
          text: "Technology Analyst Jobs In Hyderabad Secunderabad",
          url: "https://www.naukri.com/technology-analyst-jobs-in-hyderabad-secunderabad",
        },
      ],
    },
    {
      tab: "Mumbai",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Mumbai",
          url: "https://www.naukri.com/software-engineer-jobs-in-mumbai",
        },
        {
          text: "Front End Developer Jobs In Mumbai",
          url: "https://www.naukri.com/front-end-developer-jobs-in-mumbai",
        },
        {
          text: "Fullstack Developer Jobs In Mumbai",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-mumbai",
        },
        {
          text: "Technical Lead Jobs In Mumbai",
          url: "https://www.naukri.com/technical-lead-jobs-in-mumbai",
        },
        {
          text: "Ui Developer Jobs In Mumbai",
          url: "https://www.naukri.com/ui-developer-jobs-in-mumbai",
        },
        {
          text: "Web Developer Jobs In Mumbai",
          url: "https://www.naukri.com/web-developer-jobs-in-mumbai",
        },
        {
          text: "System Engineer Jobs In Mumbai",
          url: "https://www.naukri.com/system-engineer-jobs-in-mumbai",
        },
        {
          text: "Associate Jobs In Mumbai",
          url: "https://www.naukri.com/associate-jobs-in-mumbai",
        },
        {
          text: "Consultant Jobs In Mumbai",
          url: "https://www.naukri.com/consultant-jobs-in-mumbai",
        },
        {
          text: "Technology Analyst Jobs In Mumbai",
          url: "https://www.naukri.com/technology-analyst-jobs-in-mumbai",
        },
      ],
    },
    {
      tab: "Chennai",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Chennai",
          url: "https://www.naukri.com/software-engineer-jobs-in-chennai",
        },
        {
          text: "Front End Developer Jobs In Chennai",
          url: "https://www.naukri.com/front-end-developer-jobs-in-chennai",
        },
        {
          text: "Fullstack Developer Jobs In Chennai",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-chennai",
        },
        {
          text: "Technical Lead Jobs In Chennai",
          url: "https://www.naukri.com/technical-lead-jobs-in-chennai",
        },
        {
          text: "Ui Developer Jobs In Chennai",
          url: "https://www.naukri.com/ui-developer-jobs-in-chennai",
        },
        {
          text: "Web Developer Jobs In Chennai",
          url: "https://www.naukri.com/web-developer-jobs-in-chennai",
        },
        {
          text: "System Engineer Jobs In Chennai",
          url: "https://www.naukri.com/system-engineer-jobs-in-chennai",
        },
        {
          text: "Associate Jobs In Chennai",
          url: "https://www.naukri.com/associate-jobs-in-chennai",
        },
        {
          text: "Consultant Jobs In Chennai",
          url: "https://www.naukri.com/consultant-jobs-in-chennai",
        },
        {
          text: "Technology Analyst Jobs In Chennai",
          url: "https://www.naukri.com/technology-analyst-jobs-in-chennai",
        },
      ],
    },
    {
      tab: "Pune",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Pune",
          url: "https://www.naukri.com/software-engineer-jobs-in-pune",
        },
        {
          text: "Front End Developer Jobs In Pune",
          url: "https://www.naukri.com/front-end-developer-jobs-in-pune",
        },
        {
          text: "Fullstack Developer Jobs In Pune",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-pune",
        },
        {
          text: "Technical Lead Jobs In Pune",
          url: "https://www.naukri.com/technical-lead-jobs-in-pune",
        },
        {
          text: "Ui Developer Jobs In Pune",
          url: "https://www.naukri.com/ui-developer-jobs-in-pune",
        },
        {
          text: "Web Developer Jobs In Pune",
          url: "https://www.naukri.com/web-developer-jobs-in-pune",
        },
        {
          text: "System Engineer Jobs In Pune",
          url: "https://www.naukri.com/system-engineer-jobs-in-pune",
        },
        {
          text: "Associate Jobs In Pune",
          url: "https://www.naukri.com/associate-jobs-in-pune",
        },
        {
          text: "Consultant Jobs In Pune",
          url: "https://www.naukri.com/consultant-jobs-in-pune",
        },
        {
          text: "Technology Analyst Jobs In Pune",
          url: "https://www.naukri.com/technology-analyst-jobs-in-pune",
        },
      ],
    },
    {
      tab: "Kolkata",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Kolkata",
          url: "https://www.naukri.com/software-engineer-jobs-in-kolkata",
        },
        {
          text: "Front End Developer Jobs In Kolkata",
          url: "https://www.naukri.com/front-end-developer-jobs-in-kolkata",
        },
        {
          text: "Fullstack Developer Jobs In Kolkata",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-kolkata",
        },
        {
          text: "Technical Lead Jobs In Kolkata",
          url: "https://www.naukri.com/technical-lead-jobs-in-kolkata",
        },
        {
          text: "Ui Developer Jobs In Kolkata",
          url: "https://www.naukri.com/ui-developer-jobs-in-kolkata",
        },
        {
          text: "Web Developer Jobs In Kolkata",
          url: "https://www.naukri.com/web-developer-jobs-in-kolkata",
        },
        {
          text: "System Engineer Jobs In Kolkata",
          url: "https://www.naukri.com/system-engineer-jobs-in-kolkata",
        },
        {
          text: "Associate Jobs In Kolkata",
          url: "https://www.naukri.com/associate-jobs-in-kolkata",
        },
        {
          text: "Consultant Jobs In Kolkata",
          url: "https://www.naukri.com/consultant-jobs-in-kolkata",
        },
        {
          text: "Technology Analyst Jobs In Kolkata",
          url: "https://www.naukri.com/technology-analyst-jobs-in-kolkata",
        },
      ],
    },
    {
      tab: "Ahmedabad",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Ahmedabad",
          url: "https://www.naukri.com/software-engineer-jobs-in-ahmedabad",
        },
        {
          text: "Front End Developer Jobs In Ahmedabad",
          url: "https://www.naukri.com/front-end-developer-jobs-in-ahmedabad",
        },
        {
          text: "Fullstack Developer Jobs In Ahmedabad",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-ahmedabad",
        },
        {
          text: "Technical Lead Jobs In Ahmedabad",
          url: "https://www.naukri.com/technical-lead-jobs-in-ahmedabad",
        },
        {
          text: "Ui Developer Jobs In Ahmedabad",
          url: "https://www.naukri.com/ui-developer-jobs-in-ahmedabad",
        },
        {
          text: "Web Developer Jobs In Ahmedabad",
          url: "https://www.naukri.com/web-developer-jobs-in-ahmedabad",
        },
        {
          text: "System Engineer Jobs In Ahmedabad",
          url: "https://www.naukri.com/system-engineer-jobs-in-ahmedabad",
        },
        {
          text: "Associate Jobs In Ahmedabad",
          url: "https://www.naukri.com/associate-jobs-in-ahmedabad",
        },
        {
          text: "Consultant Jobs In Ahmedabad",
          url: "https://www.naukri.com/consultant-jobs-in-ahmedabad",
        },
        {
          text: "Technology Analyst Jobs In Ahmedabad",
          url: "https://www.naukri.com/technology-analyst-jobs-in-ahmedabad",
        },
      ],
    },
    {
      tab: "Gurgaon",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Gurgaon",
          url: "https://www.naukri.com/software-engineer-jobs-in-gurgaon",
        },
        {
          text: "Front End Developer Jobs In Gurgaon",
          url: "https://www.naukri.com/front-end-developer-jobs-in-gurgaon",
        },
        {
          text: "Fullstack Developer Jobs In Gurgaon",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-gurgaon",
        },
        {
          text: "Technical Lead Jobs In Gurgaon",
          url: "https://www.naukri.com/technical-lead-jobs-in-gurgaon",
        },
        {
          text: "Ui Developer Jobs In Gurgaon",
          url: "https://www.naukri.com/ui-developer-jobs-in-gurgaon",
        },
        {
          text: "Web Developer Jobs In Gurgaon",
          url: "https://www.naukri.com/web-developer-jobs-in-gurgaon",
        },
        {
          text: "System Engineer Jobs In Gurgaon",
          url: "https://www.naukri.com/system-engineer-jobs-in-gurgaon",
        },
        {
          text: "Associate Jobs In Gurgaon",
          url: "https://www.naukri.com/associate-jobs-in-gurgaon",
        },
        {
          text: "Consultant Jobs In Gurgaon",
          url: "https://www.naukri.com/consultant-jobs-in-gurgaon",
        },
        {
          text: "Technology Analyst Jobs In Gurgaon",
          url: "https://www.naukri.com/technology-analyst-jobs-in-gurgaon",
        },
      ],
    },
    {
      tab: "Noida",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs In Noida",
          url: "https://www.naukri.com/software-engineer-jobs-in-noida",
        },
        {
          text: "Front End Developer Jobs In Noida",
          url: "https://www.naukri.com/front-end-developer-jobs-in-noida",
        },
        {
          text: "Fullstack Developer Jobs In Noida",
          url: "https://www.naukri.com/fullstack-developer-jobs-in-noida",
        },
        {
          text: "Technical Lead Jobs In Noida",
          url: "https://www.naukri.com/technical-lead-jobs-in-noida",
        },
        {
          text: "Ui Developer Jobs In Noida",
          url: "https://www.naukri.com/ui-developer-jobs-in-noida",
        },
        {
          text: "Web Developer Jobs In Noida",
          url: "https://www.naukri.com/web-developer-jobs-in-noida",
        },
        {
          text: "System Engineer Jobs In Noida",
          url: "https://www.naukri.com/system-engineer-jobs-in-noida",
        },
        {
          text: "Associate Jobs In Noida",
          url: "https://www.naukri.com/associate-jobs-in-noida",
        },
        {
          text: "Consultant Jobs In Noida",
          url: "https://www.naukri.com/consultant-jobs-in-noida",
        },
        {
          text: "Technology Analyst Jobs In Noida",
          url: "https://www.naukri.com/technology-analyst-jobs-in-noida",
        },
      ],
    },
    {
      tab: "All Jobs",
      highlight: false,
      urlSet: [
        {
          text: "Software Engineer Jobs",
          url: "https://www.naukri.com/software-engineer-jobs",
        },
        {
          text: "Front End Developer Jobs",
          url: "https://www.naukri.com/front-end-developer-jobs",
        },
        {
          text: "Fullstack Developer Jobs",
          url: "https://www.naukri.com/fullstack-developer-jobs",
        },
        {
          text: "Technical Lead Jobs",
          url: "https://www.naukri.com/technical-lead-jobs",
        },
        {
          text: "Ui Developer Jobs",
          url: "https://www.naukri.com/ui-developer-jobs",
        },
        {
          text: "Web Developer Jobs",
          url: "https://www.naukri.com/web-developer-jobs",
        },
        {
          text: "System Engineer Jobs",
          url: "https://www.naukri.com/system-engineer-jobs",
        },
        {
          text: "Associate Jobs",
          url: "https://www.naukri.com/associate-jobs",
        },
        {
          text: "Consultant Jobs",
          url: "https://www.naukri.com/consultant-jobs",
        },
        {
          text: "Technology Analyst Jobs",
          url: "https://www.naukri.com/technology-analyst-jobs",
        },
      ],
    },
    {
      tab: "Top Companies",
      highlight: false,
      urlSet: [
        {
          text: "eClerx",
          url: "https://www.naukri.com/eclerx-overview-10472",
        },
        {
          text: "Infosys",
          url: "https://www.naukri.com/infosys-overview-13832",
        },
        {
          text: "CGI",
          url: "https://www.naukri.com/cgi-overview-1402790",
        },
        {
          text: "Accenture",
          url: "https://www.naukri.com/accenture-overview-10476",
        },
        {
          text: "UST",
          url: "https://www.naukri.com/ust-overview-216316",
        },
        {
          text: "Nagarro",
          url: "https://www.naukri.com/nagarro-overview-9558",
        },
        {
          text: "Conduent",
          url: "https://www.naukri.com/conduent-overview-2472988",
        },
        {
          text: "Goldman Sachs",
          url: "https://www.naukri.com/goldman-sachs-overview-530892",
        },
        {
          text: "Photon",
          url: "https://www.naukri.com/photon-overview-4619011",
        },
        {
          text: "Capgemini",
          url: "https://www.naukri.com/capgemini-overview-1288",
        },
      ],
    },
  ],
  suggesterModel: {
    qparams: {
      pFarea: 18,
    },
  },
  seo: {
    title:
      "React.js, React Developer, Mern Jobs - 17983 React.js, React Developer, Mern Job Vacancies In August 2026 - Naukri.com",
    descp:
      "17983 React.js, React Developer, Mern Jobs Available On Naukri.com. Explore React.js, React Developer, Mern Job Vacancies In Your Desired Locations Now!",
  },
  bellyFilters: {
    positions: [7, 10, 16],
    order: ["salaryRange", "citiesGid", "topGroupId"],
  },
  sid: "17867952766829450",
  isLoggedIn: true,
  variantName: "reg_embedding",
  clusterOrder: [
    "wfhType",
    "experience",
    "functionalAreaGid",
    "citiesGid",
    "salaryRange",
    "business_size",
    "roleGid",
    "glbl_RoleCat",
    "stipend",
    "internshipDuration",
    "ugCourseGid",
    "employement",
    "industryTypeGid",
    "topCompanyId",
    "topGroupId",
    "freshness",
  ],
  internshipSRP: false,
  showAgentPickedTag: false,
};
